apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-backend-demo-config
data:
  PORT: "8080"
  SERVICE_NAME: "ts-backend-demo"
  SERVICE_DESCRIPTION: "TypeScript backend demo service."
  SERVICE_VERSION: "1.0.0"
  NODE_ENV: "dev"
  OTEL_SERVICE_NAME: "ts-backend-demo"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://alloy.logging.svc.cluster.local:4318/v1/traces"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  PUBLIC_BASE_URLS: "https://ts-backend-demo.rubenspensky.com|External,http://ts-backend-demo.home.lab|Internal"
  # CORS
  CORS_ENABLED: "true"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3000,https://ts-backend-demo.rubenspensky.com,http://ts-backend-demo.home.lab"

  # OIDC / Authentik
  AUTH_PROVIDER: oidc
  AUTH_ISSUER: https://auth.rubenspensky.com/application/o/frontend-test/
  AUTH_JWKS_URL: https://auth.rubenspensky.com/application/o/frontend-test/jwks/
  AUTH_AUDIENCE: L9JCsgnMIb4CgTE3G4eSe8J5aWDTphvbpX9NM7ui

  # Scalar API docs OAuth testing
  DOCS_OAUTH_CLIENT_ID: L9JCsgnMIb4CgTE3G4eSe8J5aWDTphvbpX9NM7ui
  DOCS_OAUTH_AUTHORIZATION_URL: https://ts-backend-demo.rubenspensky.com/docs/oauth/authorize
  DOCS_OAUTH_UPSTREAM_AUTHORIZATION_URL: https://auth.rubenspensky.com/application/o/authorize/
  DOCS_OAUTH_TOKEN_URL: https://auth.rubenspensky.com/application/o/token/
  DOCS_OAUTH_REDIRECT_URI: https://ts-backend-demo.rubenspensky.com/docs
