apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-backend-demo-config
data:
  PORT: "8080"
  SERVICE_NAME: ts-backend-demo
  NODE_ENV: dev
  OTEL_SERVICE_NAME: ts-backend-demo
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://alloy.logging.svc.cluster.local:4317"
