apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-backend-demo
  labels:
    app.kubernetes.io/name: ts-backend-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ts-backend-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ts-backend-demo
    spec:
      containers:
        - name: ts-backend-demo
          image: ghcr.io/rubenspensky-homelab/ts-backend-demo:3845959183cdd55b33545055eb18f28fe32346cd
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: ts-backend-demo-config
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
