apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ts-backend-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ts-backend-demo

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
